i = imread('D:\muniat.jpg')
subplot(3,3,1)
imshow(i)
subplot(3,3,2)
gray=rgb2gray(i)
imshow(gray)
subplot(3,3,3)
b=im2bw(i)
imshow(b)
subplot(3,3,4)
c=imadjust(gray)
imshow(c)
imwrite(i,'D:\muniat2.jpg')
d=imread('D:\muniat2.jpg')
subplot(3,3,5)
imshow(d)
title('Write image')